name = "Loma"
license = "AGPLv3"
licenselink = "https://www.gnu.org/licenses/agpl-3.0.en.html"
description = "A minimal and easily re-configured theme utilizing little to no JS."
homepage = "https://nora.codes"
tags = ["minimal", "blog", "personal", "simple", "clean", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Leonora Tindall"
  homepage = "https://nora.codes"

