baseURL = "https://leotindall.com/"
languageCode = "en-us"

title = "Leo Tindall"
theme = "hugo-classic-mod"

# dateFormat = "date -u +'%Y-%m-%d %R:%S%:z'"

# Allow Hugo to munge, e.g., "Programming Stuff" into "programming-stuff"
preserveTaxonomyNames = false

# Allow Hugo to rewrite URLs so they work on IPFS as well as locally and
# on leotindall.com
relativeURLs = true

# Highlighting
pygmentsStyle = "fruity"
pygmentsUseClassic = false
pygmentsCodefences = true

[taxonomies]
  category = "categories"

[permalinks]
    post = "/post/:slug"
    tutorial = "/tutorial/:slug"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Tutorials"
    url = "/tutorial/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[[menu.feed]]
    name = "✍"
    url = "https://pad.leotindall.com/"
    weight = 5

[[menu.feed]]
    name = "🔄"
    url = "https://git.leotindall.com/"
    weight = 4

[[menu.feed]]
    name = "📹"
    url = "https://vid.leotindall.com/"
    weight = 3

[[menu.feed]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 1



[params]
    description = "Leo Tindall's personal website"
    footer = "Text: [CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) ≥ 4 | Code: [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) ≥ v3 | Font: [Bitter ht](https://www.huertatipografica.com/en/fonts/bitter-ht), [OFL](https://en.wikipedia.org/wiki/SIL_Open_Font_License) | ![GNU Natalie Nguyen](/images/tipsytentacle.gif) | [No AMP](https://www.polemicdigital.com/google-amp-go-to-hell/)"
