baseURL = "https://leotindall.com/"
languageCode = "en-us"

title = "Leo Tindall"
theme = "hugo-classic-mod"

# dateFormat = "date -u +'%Y-%m-%d %R:%S%:z'"

# Allow Hugo to munge, e.g., "Programming Stuff" into "programming-stuff" 
preserveTaxonomyNames = false

# Highlighting
pygmentsStyle = "fruity"
pygmentsUseClassic = false
pygmentsCodefences = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
    post = "/post/:slug"
    tutorial = "/tutorial/:slug"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Tutorials"
    url = "/tutorial/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Leo Tindall's personal website"
    footer = "[GitHub](https://github.com/LeoTindall) | [@Tindall@Cybre.Space](https://cybre.space/@tindall) | [CC-BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) | ![GNU Natalie Nguyen](/images/tipsytentacle.gif)"